CREATE TABLE IF NOT EXISTS `purchase_settlements` (
  `id`               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id`        BIGINT UNSIGNED NOT NULL,
  `settlement_no`    VARCHAR(50)     NOT NULL,
  `match_id`         BIGINT UNSIGNED NOT NULL COMMENT '来源三单匹配记录 ID',
  `po_id`            BIGINT UNSIGNED NOT NULL,
  `delivery_note_id` BIGINT UNSIGNED NOT NULL,
  `receipt_id`       BIGINT UNSIGNED NOT NULL,
  `supplier_id`      BIGINT UNSIGNED NOT NULL,
  `total_amount`     DECIMAL(16,2)   NOT NULL DEFAULT 0,
  `status`           ENUM('draft','confirmed','paid','cancelled') NOT NULL DEFAULT 'draft',
  `due_date`         DATE            DEFAULT NULL,
  `confirmed_by`     BIGINT UNSIGNED DEFAULT NULL,
  `confirmed_at`     DATETIME(3)     DEFAULT NULL,
  `paid_at`          DATETIME(3)     DEFAULT NULL,
  `notes`            VARCHAR(500)    DEFAULT NULL,
  `created_at`       DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`       DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by`       BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `updated_by`       BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_settlement_no` (`tenant_id`, `settlement_no`),
  KEY `idx_purchase_settlement_match` (`tenant_id`, `match_id`),
  KEY `idx_purchase_settlement_po` (`tenant_id`, `po_id`),
  KEY `idx_purchase_settlement_status` (`tenant_id`, `status`),
  KEY `idx_purchase_settlement_supplier` (`tenant_id`, `supplier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购结算单';
